name: Run Python Script

on: push
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # Use the version you need

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install python-dotenv selenium webdriver-manager

      - name: Run script
        run: python main.py
        # Replace 'your_script_name.py' with the name of your Python script
